version: '3.2'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: car-rental-ca-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: car-rental-ca
      MYSQL_PASSWORD: car-rental-ca
      MYSQL_DATABASE: car-rental-ca
    volumes:
      - ./:/var/www
    networks:
      - car-rental-ca-network
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: 'car-rental-ca-nginx'
    ports:
      - '8001:80'
      - '7001:443'
    privileged: true
    volumes:
      - ./:/var/www
      - ./docker/nginx/certs/certificate.crt:/etc/nginx/conf.d/certificate.crt
      - ./docker/nginx/certs/certificate.key:/etc/nginx/conf.d/certificate.key
      - ./docker/nginx/log:/var/log/nginx
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: 'car-rental-ca-php'
    networks:
      - default
      - car-rental-ca-network
    privileged: true
    volumes:
      - ./:/var/www
      - ./docker/php/log:/var/log/php
networks:
  car-rental-ca-network:
    external: true
